[versions]
kotlin = "2.3.10"
kotest = "6.1.3"
junit = "6.0.3"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.0.1" }

[libraries]
awaitility = { module = "org.awaitility:awaitility-kotlin", version = "4.3.0" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
kotest = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version = "1.14.9" }
slf4j = {module="org.slf4j:slf4j-api", version = "2.0.17"}